namespace: "db"

group:
  match:
    label_team: "database"
routes:
  - receiver: "critical"
    match:
      severity: "critical"
    group_by: [alertname, db_instance]
    group_wait: 30s
    repeat_interval: 1h

  - receiver: "warning"
    match:
      severity: "warning"
    group_wait: 5m
    repeat_interval: 4h

  - receiver: "warning"
    match:
      severity: "info"
    group_wait: 10m
    repeat_interval: 12h

receivers:
  - name: "critical"
    slack_configs:
      - channel: "#db-alerts-critical"
        send_resolved: true
    pagerduty_configs:
      - routing_key: "db-pd-routing-key"
        send_resolved: true

  - name: "warning"
    slack_configs:
      - channel: "#db-alerts"
        send_resolved: true
