version: 2

project_name: litmus

before:
  hooks:
    - npm --prefix ui ci --prefer-offline
    - npm --prefix ui run build

builds:
  - id: litmus
    main: .
    binary: litmus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - .gitattributes
      - README.md
      - LICENSE
      - docs/**/*

release:
  github:
    owner: nyambati
    name: litmus
  draft: true
  prerelease: auto
  name_template: '{{.Version}}'

dockers:
  - image_templates:
      - "ghcr.io/nyambati/litmus:{{ .Tag }}"
      - "ghcr.io/nyambati/litmus:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--build-arg=VERSION={{.Version}}"
    goos: linux
    goarch: amd64

  - image_templates:
      - "ghcr.io/nyambati/litmus:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--build-arg=VERSION={{.Version}}"
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/nyambati/litmus:{{ .Tag }}"
    image_templates:
      - "ghcr.io/nyambati/litmus:{{ .Tag }}"
      - "ghcr.io/nyambati/litmus:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/nyambati/litmus:latest"
    image_templates:
      - "ghcr.io/nyambati/litmus:{{ .Tag }}"
      - "ghcr.io/nyambati/litmus:{{ .Tag }}-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
