version: 2

project_name: litmus

before:
  hooks:
    - npm --prefix ui ci --prefer-offline
    - npm --prefix ui run build

builds:
  - id: litmus
    main: .
    binary: litmus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - docs/**/*

release:
  github:
    owner: nyambati
    name: litmus
  draft: true
  prerelease: auto
  name_template: '{{.Version}}'

dockers_v2:
  - images:
      - "ghcr.io/nyambati/litmus"
    tags:
      - "{{ .Tag }}"
      - "latest"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
    build_args:
      VERSION: "{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
