
config:
    directory: config
    file: alertmanager.yaml
    templates: templates/
global_labels:
    cluster: production
    severity: warning
mimir:
    address: "localhost:8080"
    api_key: ""
    tenant_id: ""
regression:
    directory: config/regressions/
    keep: 5
tests:
    directory: config/tests/
