workspace:
  root: "example" # The Root Package directory
  fragments: "fragments/*" # Glob pattern (Relative to root by default)
  history: 5 # Number of regression baselines to keep
policy:
  # require_tests: true
  skip_root: true
  enforce:
    strict: false
    matchers:
      - severity
      - label_team
mimir:
  address: "localhost:8080"
  api_key: ""
  tenant_id: ""
