workspace:
  root: "config" # The Root Package directory
  fragments: "fragments/*" # Glob pattern (Relative to root by default)
  history: 5 # Number of regression baselines to keep
global_labels:
  cluster: production
  severity: warning
policy:
  require_tests: true
  enforce_matchers:
    - severity
    - label_team
mimir:
  address: "localhost:8080"
  api_key: ""
  tenant_id: ""
